languageCode = 'en-us'
title = 'GxbNt Notes'
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

pagination.pagerSize=10 # articles per page

[params]
	mode="auto" # color-mode â†’ light,dark or auto
	featherIconsCDN=true
	subtitle = "GxbNt Notes"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/GxbNt"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/GxbNt0x01"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
icon_pack = "fab"
url = "https://www.linkedin.com/in/gxbnt/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/posts/who-am-i/"
weight = 3

